server:
  port: 8011
  tomcat:
    uri-encoding: UTF-8
spring:
  profiles:
    active: dev
  ############################ KAFKA #########################
  kafka:
    bootstrap-servers: 47.100.81.35:9092
    #    bootstrap-servers: 192.168.1.245:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: asd
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

#task:
appName: SerachJob
sparkHome: /opt/cloudera/parcels/CDH-6.0.1-1.cdh6.0.1.p0.590678/lib/spark
appResource: /YunLiKe/jar/taihe/serach/serach-data-1.0-SNAPSHOT-jar-with-dependencies.jar
mainClass: com.taihe.serach.SerachJob
